#sensor:
- platform: template
  scan_interval: 100
  sensors:
    glances:
      friendly_name: "ZTE SMS Data checker"
      value_template: >-
        {% if state_attr('sensor.zte_last_sms_values', 'content') == "Za nastavak surfanja po maksimalnoj dostupnoj brzini posaljite rijec BRZINA na broj 13909. Vas Hrvatski Telekom" %}
          "Data Plan Expired"
        {% elif state_attr('sensor.zte_last_sms_values', 'content') == "Pogresna kljucna rijec." %}
          "Data Plan Expired"
        {% else %}
          "Data Plan Active"
        {% endif %}


- platform: template
  sensors:
    zte_network_type:
      friendly_name: "Network type"
      value_template: "{{ state_attr('sensor.zte_router_info', 'network_type') }}"
    zte_signal_bar:
      friendly_name: "Signal Bar"
      value_template: "{{ state_attr('sensor.zte_router_info', 'signalbar') }}"
    zte_router_version:
      friendly_name: "Router Firmware version"
      value_template: "{{ state_attr('sensor.zte_router_info', 'wa_inner_version') }}"
    zte_wan_ipaddr:
      friendly_name: "WAN IP address"
      value_template: "{{ state_attr('sensor.zte_router_info', 'wan_ipaddr') }}"
    zte_5g_sinr:
      friendly_name: "5G SINR"
      value_template: "{{ state_attr('sensor.zte_router_info', 'Z5g_SINR') }}"
      unit_of_measurement: "dB"
    zte_5g_rsrp:
      friendly_name: "5G RSRP"
      value_template: "{{ state_attr('sensor.zte_router_info', 'Z5g_rsrp') }}"
      unit_of_measurement: "dBm"
    zte_5g_cell_id:
      friendly_name: "5G Band"
      value_template: "{{ state_attr('sensor.zte_router_info', 'nr5g_action_band') }}"
    zte_5g_snr:
      friendly_name: "5G Channel id"
      value_template: "{{ state_attr('sensor.zte_router_info', 'nr5g_action_channel') }}"
    zte_lte_rsrq:
      friendly_name: "RSRQ"
      value_template: "{{ state_attr('sensor.zte_router_info', 'lte_rsrq') }}"
      unit_of_measurement: "dBm"
    zte_lte_rsrp:
      friendly_name: "RSRP"
      value_template: "{{ state_attr('sensor.zte_router_info', 'lte_rsrp') }}"
      unit_of_measurement: "dBm"
    zte_cell_id:
      friendly_name: "Cell ID"
      value_template: "{{ state_attr('sensor.zte_router_info', 'cell_id') |int(base=16) }}"
    zte_lte_snr:
      friendly_name: "LTE SNR"
      value_template: "{{ state_attr('sensor.zte_router_info', 'lte_snr') }}"
      unit_of_measurement: "dB"
    zte_wan_active_channel:
      friendly_name: "WAN active channel"
      value_template: "{{ state_attr('sensor.zte_router_info', 'wan_active_channel') }}"
    zte_wan_active_band:
      friendly_name: "WAN main active band"
      value_template: "{{ state_attr('sensor.zte_router_info', 'wan_active_band') }}"
    zte_lte_multi_ca_scell_info:
      friendly_name: "Multi cell info"
      value_template: "{{ state_attr('sensor.zte_router_info', 'lte_multi_ca_scell_info') }}"

    zte_lte_ca_pcell_band:
      friendly_name: "PA cell band"
      value_template: "{{ state_attr('sensor.zte_router_info', 'lte_ca_pcell_band') }}"
    zte_lte_ca_pcell_bandwidth:
      friendly_name: "PA cell bandwidth"
      value_template: "{{ state_attr('sensor.zte_router_info', 'lte_ca_pcell_bandwidth') }}"
      unit_of_measurement: "Mhz"

    zte_lte_monthly_transfer_usage:
      friendly_name: "Monthly usage"
      value_template: '{{ ((state_attr("sensor.zte_router_info", "monthly_tx_bytes") |float + state_attr("sensor.zte_router_info", "monthly_rx_bytes") |float ) / 1024 / 1024 / 1024) | round(2) }}'
      unit_of_measurement: "GB"
    zte_lte_monthly_transfer_left:
      friendly_name: "Data left"
      value_template: >-
        {% if states("sensor.zte_lte_monthly_transfer_usage") | float < 200 %}
          {{ ( 200 - states("sensor.zte_lte_monthly_transfer_usage") | float ) | round(2) }}
        {% else %}
          {{ ( 50 - states("sensor.zte_lte_monthly_transfer_usage") | float %50 ) | round(2) }}
        {% endif %}
      unit_of_measurement: "GB"
    zte_connection_uptime:
      friendly_name: "Connection uptime"
      value_template: '{{ ((state_attr("sensor.zte_router_info", "realtime_time") |float) / 3600 ) | round(2) }}'
      unit_of_measurement: "hour(s)"
#test
#    zte_realtime_download_speed:
#      friendly_name: "Realtime download speed"
#      unique_id: sensor.zte_realtime_download_speed
#      value_template: '{{ ((state_attr("sensor.zte_router_info", "realtime_rx_thrpt") |float) / 1024 / 1024) | round(2) }}'
#      unit_of_measurement: "MB/s"
#    zte_realtime_upload_speed:
#      friendly_name: "Realtime upload speed"
#      unique_id: sensor.zte_realtime_upload_speed
#      value_template: '{{ ((state_attr("sensor.zte_router_info", "realtime_tx_thrpt") |float) / 1024 / 1024) | round(2) }}'
#      unit_of_measurement: "MB/s"
