alias: Clean SMS Memory
description: Clean SMS Memory
trigger:
  - platform: state
    entity_id:
      - sensor.zte_sms_memory_left
    to: "\"You have 0 messages left of 100\""
condition:
  - condition: state
    entity_id: sensor.zte_sms_memory_left
    state: "\"You have 0 messages left of 100\""
action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.zte_delete_sms_py
mode: single
