name: Increment Version and Release

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Read current version
      id: read_version
      run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

    - name: Increment version
      id: increment_version
      run: echo "VERSION=$(( $(echo $VERSION | cut -d. -f1) + 1 )).0.0" >> $GITHUB_ENV

    - name: Update version file
      run: echo "VERSION=${{ steps.increment_version.outputs.VERSION }}" > VERSION

    - name: Zip files
      run: zip -r ZTE_MC_HA_v${{ steps.increment_version.outputs.VERSION }}.zip .

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.increment_version.outputs.VERSION }}
        release_name: Release v${{ steps.increment_version.outputs.VERSION }}
        body: |
          Changes in this release:
          - Describe your changes here

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./ZTE_MC_HA_v${{ steps.increment_version.outputs.VERSION }}.zip
        asset_name: ZTE_MC_HA_v${{ steps.increment_version.outputs.VERSION }}.zip
        asset_content_type: application/zip
